anything = ['songshan', 'changjiang', 'China', 'beijing', 'Chinese', 'computer']
print(anything)
anything.append('book')
print(anything)
anything.insert(0, 'huangshan')
print(anything)
del anything[0]
print(anything)
anything.pop()
print(anything)
anything.remove('computer')
print(anything)
print(sorted(anything))
print(anything)
anything.sort()
print(anything)
print(anything)
anything.reverse()
print(anything)
print(len(anything))
