going_places = ['chengdu', 'xian', 'suzhou', 'dali', 'beijing']
print(going_places)
print(sorted(going_places))
print(going_places)
print(sorted(going_places, reverse=True))
print(going_places)
going_places.reverse()
print(going_places)
going_places.reverse()
print(going_places)
going_places.sort()
print(going_places)
going_places.sort(reverse=True)
print(going_places)
